config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :docs
  authenticated :user do
    root "docs#index", as: "authenticated_root"
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
    @docs = Doc.where(user_id: current_user)
  end

  def new
    @doc = current_user.docs.build
  end

  def show
  end

  def create

    @doc = current_user.docs.build(doc_params)

    if @doc.save
      redirect_to @doc
    else
      render 'new'
    end

  end

  def edit
  end

  def update
    if @doc.update(doc_params)
      redirect_to @doc
    else
      render 'edit'
    end
  end

  def destroy
    @doc.destroy
    redirect_to docs_path
  end

  private
    def find_doc
      @doc = Doc.find(params[:id])
    end

    def doc_params
      params.require(:doc).permit(:title, :content)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.erb
<%= form_for @doc do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.button :submit, class: "button" %>
<% end %>

app/views/docs/edit.html.erb
<section class="wrapper_with_padding">
    <h1>Fix It</h1>
    <%= render 'form'%>
    <p><%=link_to "Cancel", doc_path%></p>
</section>  

app/views/docs/index.html.erb
<section id= "docs" class= "wrapper_with_padding clearfix">
    <%unless @docs.blank?%>
        <%@docs.each do |doc| %>
            <%=link_to doc_path(doc.id) do %> <!--This will surround the div with <a> tags making everithing a link-->
                <div class="doc">
                    <p class="title"><%=doc.title%></p>
                    <p class="date"><%=time_ago_in_words(doc.created_at)%></p>
                    <p class="content"><%=truncate(doc.content, length:50)%></p> <!--  this is coming from timestamps and it will show the timw when the doc was created -->
                     <!--  to show just the 50 first characters -->
                </div>
            <%end%>
        <%end%>
    <%else%>
        <h2>Create Doc!</h2>
        <p>Start Creating documents and Organizing your life!</p>
        <button><%= link_to "Create Doc", new_doc_path%></button>
    <%end%>
</section>

app/views/docs/new.html.erb
<section class="wrapper_with_padding">
    <h1>New Doc</h1>
    <%= render 'form'%>
</section>

app/views/docs/show.html.erb
<section id= "doc_show" class= "wrapper_with_padding ">
    <h1 class="title"><%= @doc.title%></h1>
    
    <!--Returns text transformed into HTML using simple formatting rules.
    Two \n\n are considered as a paragraph and wrapped in <p>. One newline (\n)
    is considered as a linebreak and a <br /> tag is appended.-->
    
    <p><%= simple_format(@doc.content)%></p> 
    <div>
        <%= link_to "Fix Doc", edit_doc_path(@doc), class: "button"%>
        <%= link_to 'Delete',@doc,data: {turbo_method: 'delete', turbo_confirm: "Are you sure"},class:"button"%>
    </div>    
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReminderHub | Save your Document</title>
    <%= stylesheet_link_tag "application.css", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tag %>
    <%= turbo_include_tags %>
  </head>
  <body>
    <header>
      <div class="header_inner">
        <%= link_to "DocumentLocker", root_path, id: 'logo' %>
        
        <nav>
          <% if user_signed_in? %>
            <%= link_to "Create Doc", new_doc_path %>
            <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %>
          <% end %>
        </nav>
      </div>
    </header>
    
    <p class="notice"><%= notice %></p>
    <div class="alert"><%= alert %></div>
    
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<!-- #banner -->
<div id="banner">
  <div class="banner_content">
    <h1>FileCabinet</h1>
    <p>Your life's work. Organized, always.</p>
    <button><%= link_to "Enter", new_user_registration_path %></button>
  </div>
</div>

<!-- #callouts -->
<div id="callouts">
  <div class="callout_inner">
    <div class="wrapper">
      <div class="callout">
        <h2>Organize</h2>
        <p>"
Document organization is crucial for efficiency and clarity. Properly structured documents enhance accessibility and retrieval, facilitating streamlined workflows. Clear categorization, logical hierarchies, and standardized naming conventions contribute to a systematic approach. Efficient document organization ensures quick identification of relevant information, reducing confusion and improving overall productivity in various professional and personal contexts"</p>
      </div>
    </div>
  </div>
</div>

<!-- #bottom_cta -->
<div id="bottom_cta" class="wrapper">
  <h2>Go Ahead</h2>
  <br>
  <button><%= link_to "Join Now", new_user_registration_path %></button>
</div>